name: Popose a new BB
description: File a proposal for a new BB.
title: "[New BB]:"
labels: [BB]

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this form!

- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: e.g. email@example.com
  validations:
    required: false

- type: input
  id: name
  attributes:
    label: Name of the BB
    description: Insert name of the BB
    placeholder: e.g. Diagnostic Policy Manager
  validations:
    required: true


- type: checkboxes
  id: BB_tags
  attributes:
    label: BB Tags(s)
    description: Tag(s) define in which area(s) (cloud, in-vehicle) the BB is executed, and what type of BB it is (tool, process, microservice)
    options:
      - label: BB-SC
      - label: BB-CSC
      - label: BB-MU
      - label: BB-CMU
      - label: BB-EST
      - label: BB-CEST
      - label: S-BB
      - label: FC
      - label: BB-SC-TC
      - label: BB-CSC-TC
      - label: BB-WE
  validations:
    required: true

- type: input
  id: BB_tags_main
  attributes:
    label: Main BB Tag
    description: Out of the BB Tags you selected, wich is the most important one?
    placeholder: e.g. BB-SC
  validations:
    required: true

- type: input
  id: FC
  attributes:
    label: Functional Clusters
    description: In which Functional Cluster the BB be located; if none of the existing fit new required
    placeholder: e.g. Communication
  validations:
    required: true

- type: dropdown
  id: layer
  attributes:
    label: Layer
    description: Please select the corresponding Layer of the affected BB
    multiple: true
    options:
    - AppLayer
    - MWLayer
    - OSLayer
    - HWLayer
  validations:
    required: true

- type: input
  id: known_impl
  attributes:
    label: Known Implementation(s)
    description: Link or description of known implementations
    placeholder: 
  validations:
    required: true

- type: input
  id: id
  attributes:
    label: ID (unique name)
    description: 
    placeholder: 
  validations:
    required: false

- type: input
  id: description
  attributes:
    label: Description
    description: General Description of the BB
    placeholder: 
  validations:
    required: true

- type: input
  id: rationale
  attributes:
    label: Rationale
    description: Explanation why we need the BB; what problem want to be solved
    placeholder: 
  validations:
    required: false