name: Popose a new BB
description: File a proposal for a new BB.
title: "[New BB]:"
labels: [BB]

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this form!

- type: textarea
  id: problem-description
  attributes:
    label: Problem Description
    description: Please describe the problem you encountered in detail
  validations:
    required: true
